source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!


# Core
pod 'Liferay-iOS-SDK', '6.2.0.22'
pod 'Liferay-OAuth', '0.1.1'
pod 'MBProgressHUD', '0.9.1'
pod 'SMXMLDocument', '1.1'
pod 'ODRefreshControl', '1.2'
pod 'YapDatabase', '2.6.5'
pod 'Sugar', '~> 1.0.2'

# Login & signup: save credentials
pod 'KeychainAccess', '2.3.1'

# UserPortrait
pod 'CryptoSwift', '0.1.1'

# DDLForm
pod 'DTPickerPresenter', '0.2.0'
pod 'TNRadioButtonGroup', '0.4'
pod 'MDRadialProgress', '1.3.2'

# EE version
pod 'PasscodeLock', :git => 'https://github.com/velikanov/SwiftPasscodeLock', :tag => '1.0.2'



target :LiferayScreensTests do
	pod 'Nocilla'
	pod 'SwiftTryCatch'
end

